### ISSUE TITLE
No password protection for retired challenges write ups

### ISSUE THREAD

**Issue by kush9408** [Hackplayers/hackthebox-writeups#217]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kush9408** [comment]
As those challenges are retired password protection should be removed in order for other people who were not able to solve those challenge could read the write-ups and learn from it.

**Comment by OscarAkaElvis** [comment]
yeah you can do it... fork the repo, open all retired pdfs, save them again without password and to a Pull Request with the changes. Thanks.
