### ISSUE TITLE
PDF is locked. I can not find the password.

### ISSUE THREAD

**Issue by syedalizain033** [Hackplayers/hackthebox-writeups#226]
Hi. I downloaded the pdf but it is locked. Can I know the password here. I needed that on urgent basis and can not find the password, If you could share here, it would be helpful to others as well.

**Comment by OscarAkaElvis** [comment]
looooooooool yeah, it is locked intentionally. The flag is the password to open it. You can't open it if you don't know the flag. So the write-ups are to check how others did the same work you did. If you didn't solve yet the challenge or the machine, you can't access to it.
