### ISSUE TITLE
password for pdf 

### ISSUE THREAD

**Issue by sangeeta667143** [Hackplayers/hackthebox-writeups#24]
HI , 

pLEASE PROVIDE THE PASSWPRD FOR THE Stratosphere.PDF

**Comment by crysthofferattier** [comment]
Important All Challenge Writeups are password protected with the corresponding flag.
Active machines writeups are protected with the corresponding root flag.

**Comment by sizar3x** [comment]
plzzzzz tell us the password?plzz

**Comment by sizar3x** [comment]
corresponding flag?

**Comment by sizar3x** [comment]
[oscarakaelvis-i_know_mag1k.rar.pdf](https://github.com/Hackplayers/hackthebox-writeups/files/2377944/oscarakaelvis-i_know_mag1k.rar.pdf)
pass please bro

**Comment by vmotos** [comment]
the password is the flag.... so you must to complete the corresponding writeup first...
