### ISSUE TITLE
Invalid password for Embryonic Plant

### ISSUE THREAD

**Issue by Antonis-Para** [Hackplayers/hackthebox-writeups#288]
Hi, can you check the password of Embryonic Plant? I have solved the challenge and posted on HTB, it got accepted. So im not sure if im doing something wrong here, the format im using is HTB{...}.
Thanks

**Comment by OscarAkaElvis** [comment]
I double checked it. Password is ok. At least the password I have.

Probably htb changed the challenge and the flag. On my profile you can find my email. Send me an email with the current flag. I'll check it. Thanks.

Closing.
