### ISSUE TITLE
irked - PDF Password is wrong

### ISSUE THREAD

**Issue by atombug** [Hackplayers/hackthebox-writeups#31]
## Machine - irked

`ozunu-irked.pdf` can not be opened with **root flag**, tried user flag also. 
However I am able to open `giru-irked.pdf` which is for the same machine.

**Comment by ForeGuards** [comment]
I could open both writeups with the root flag of ozunu-irked.pdf

**Comment by 0xRick** [comment]
I'm having the same problem 
I can open `giru-irked.pdf` but can't open `ozunu-irked.pdf`

**Comment by ForeGuards** [comment]
Really? can you send me please your flag? 
info@whitehathacker.info

**Comment by 0xRick** [comment]
@WhiteHat-Hacking 
Done

**Comment by ForeGuards** [comment]
I don't know what's wrong, everybody on my team could open the writeup. and with your flag @0xRick I could also open it.

**Comment by atombug** [comment]
@0xRick Then I would like suggest that you should update yours pdf once again.

**Comment by atombug** [comment]
@WhiteHat-Hacking Then I would like to suggest that you should update yours pdf once again.

**Comment by atombug** [comment]
@WhiteHat-Hacking @vmotos Then I would like to suggest that you should update yours pdf once again. This issue is like : code works on my laptop but not working in prod. env. :confused:

**Comment by atombug** [comment]
Can anyone update this pdf?

**Comment by atombug** [comment]
What is taking so long TO RESOLVE THIS ISSUE? @vmotos

**Comment by ForeGuards** [comment]
please try with this online viewer
pdfviewer.softgateon.net

**Comment by Crow1401** [comment]
Please help me, how can I find the root flag?
