### ISSUE TITLE
Sizzle write up missing

### ISSUE THREAD

**Issue by Christopher-APPL** [Hackplayers/hackthebox-writeups#40]
Hi, 
First of this is a nice repo, it helps a lot to clarify ideas after completing a box, because nine times out of ten I hear from people that there is a different way to root them.
after completing sizzle was wondering if my user approach with wireshark was coherent, but the write up seems like it's missing. 
Kind regards, Chris

**Comment by vmotos** [comment]
We've added two writeups for Sizzle machine.
