### ISSUE TITLE
Bastion

### ISSUE THREAD

**Issue by breakndenter** [Hackplayers/hackthebox-writeups#45]
Bastion password is wrong

**Comment by lduros** [comment]
+1

**Comment by OscarAkaElvis** [comment]
wtf?? Bastion from Wilson is ok... is the fourth issue talking about bad password for wilson write-ups and all of them are ok....

**Comment by lduros** [comment]
I've been trying to open them (bastion and swagshop) with evince, maybe it's a software issue with the pdf generation and the evince reader? What are you using?

**Comment by OscarAkaElvis** [comment]
Adobe Acrobat Reader DC on windows. Believe me, they are working.

**Comment by lduros** [comment]
Then it must be an issue with the pdf version/encryption and evince (the default pdf reader in gnome i believe) on linux for me. I'll check on windows shortly.
