### ISSUE TITLE
Onetwoseven incorrect password for Wilson

### ISSUE THREAD

**Issue by shulhi** [Hackplayers/hackthebox-writeups#46]
Password for PDF wilson-onetwoseven is invalid when I pasted root flag. The other PDF (fiti) is readable with root flag.

**Comment by lduros** [comment]
It's very odd that it seems all the walkthrough by the same author have the same issue. Bastion has the wrong password too...

**Comment by OscarAkaElvis** [comment]
The password is ok... what the hell are you trying to do? is the third issue about this... the three about the same author. I tested all of them and the password is the root flag, is ok.

**Comment by n0tduck1e** [comment]
i have the same issue root flag is accepted by hackthebox but not correct password for the pdf

**Comment by OscarAkaElvis** [comment]
Try it on other operating system or other pdf viewer. Look at this: https://github.com/Hackplayers/hackthebox-writeups/issues/45

They are working. Locking.
